// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoprulrtfxbmbgrbaxgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcHJ1bHJ0ZnhibWJncmJheGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODM2OTgsImV4cCI6MjA3MjY1OTY5OH0.8goHJ8JfORAI7v8i-gntfiqfSGwE5mN-E2Bvqm2K7FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});